/**
* VkRadixSort written by Mirco Werner: https://github.com/MircoWerner/VkRadixSort
* Based on implementation of Intel's Embree: https://github.com/embree/embree/blob/v4.0.0-ploc/kernels/rthwif/builder/gpu/sort.h
*/

/**
* This shader is modified from the original to support 64-bit k-v pairs.
* The license of the original code is as follows:

    MIT License

    Copyright (c) 2023 Mirco Werner

    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.

*/

#version 460
#extension GL_GOOGLE_include_directive: enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable
#include "../shared_constants.glsl"

#define WORKGROUP_SIZE VKGS_WORKGROUP_SIZE
#define RADIX_SORT_BINS VKGS_RADIX_SORT_BINS
#define FLAG_WORD_BITS 32U

layout (local_size_x = WORKGROUP_SIZE) in;

layout (push_constant, std430) uniform PushConstants {
    uint g_num_elements;
    uint g_shift;
    uint g_num_workgroups;
    uint g_num_blocks_per_workgroup;
};

layout (std430, set = 0, binding = 0) buffer elements_in {
    uint64_t g_elements_in[];
};

layout (std430, set = 0, binding = 1) buffer elements_out {
    uint64_t g_elements_out[];
};

layout (std430, set = 0, binding = 2) buffer payload_in {
    uint g_payload_in[];
};

layout (std430, set = 0, binding = 3) buffer payload_out {
    uint g_payload_out[];
};

layout (std430, set = 0, binding = 4) buffer histograms {
    uint g_histograms[];
};

shared uint bin_totals[RADIX_SORT_BINS];
shared uint global_offsets[RADIX_SORT_BINS];

struct BinFlags {
    uint flags[WORKGROUP_SIZE / FLAG_WORD_BITS];
};
shared BinFlags bin_flags[RADIX_SORT_BINS];

void main() {
    uint lID = gl_LocalInvocationID.x;
    uint wID = gl_WorkGroupID.x;

    uint local_histogram = 0;
    if (lID < RADIX_SORT_BINS) {
        uint count = 0;
        for (uint j = 0; j < g_num_workgroups; j++) {
            const uint t = g_histograms[RADIX_SORT_BINS * j + lID];
            local_histogram = (j == wID) ? count : local_histogram;
            count += t;
        }
        bin_totals[lID] = count;
    }
    barrier();

    if (lID < RADIX_SORT_BINS) {
        uint global_histogram = 0;
        for (uint bin = 0; bin < lID; bin++) {
            global_histogram += bin_totals[bin];
        }
        global_offsets[lID] = global_histogram + local_histogram;
    }
    barrier();

    const uint flags_bin = lID / FLAG_WORD_BITS;
    const uint flags_bit = 1U << (lID % FLAG_WORD_BITS);

    for (uint index = 0; index < g_num_blocks_per_workgroup; index++) {
        uint elementId = wID * g_num_blocks_per_workgroup * WORKGROUP_SIZE + index * WORKGROUP_SIZE + lID;

        if (lID < RADIX_SORT_BINS) {
            for (uint i = 0; i < WORKGROUP_SIZE / FLAG_WORD_BITS; i++) {
                bin_flags[lID].flags[i] = 0U;
            }
        }
        barrier();

        uint64_t element_in = 0;
        uint payload_in = 0;
        uint binID = 0;
        uint binOffset = 0;
        if (elementId < g_num_elements) {
            element_in = g_elements_in[elementId];
            payload_in = g_payload_in[elementId];
            binID = uint(element_in >> g_shift) & uint(RADIX_SORT_BINS - 1);
            binOffset = global_offsets[binID];
            atomicOr(bin_flags[binID].flags[flags_bin], flags_bit);
        }
        barrier();

        if (elementId < g_num_elements) {
            uint prefix = 0;
            uint count = 0;
            for (uint i = 0; i < WORKGROUP_SIZE / FLAG_WORD_BITS; i++) {
                const uint bits = bin_flags[binID].flags[i];
                const uint full_count = bitCount(bits);
                const uint partial_count = bitCount(bits & (flags_bit - 1));
                prefix += (i < flags_bin) ? full_count : 0U;
                prefix += (i == flags_bin) ? partial_count : 0U;
                count += full_count;
            }
            g_elements_out[binOffset + prefix] = element_in;
            g_payload_out[binOffset + prefix] = payload_in;
            if (prefix == count - 1) {
                atomicAdd(global_offsets[binID], count);
            }
        }

        barrier();
    }
}
